[package]
name = "Helloworldsampleenclave"
version = "1.0.0"
edition = "2018"

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
async-rt = { path = "../../../../async-rt", features = ["sgx", "auto_run"] }
async-socket = { path = "../../../../async-socket", features = ["sgx"] }
io-uring-callback = { path = "../../../../io-uring-callback", features = ["sgx"] }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../../../../../../deps/rust-sgx-sdk/sgx_types" }
sgx_tstd = { path = "../../../../../../../deps/rust-sgx-sdk/sgx_tstd", features = ["backtrace", "thread"] }
sgx_trts = { path = "../../../../../../../deps/rust-sgx-sdk/sgx_trts" }

[workspace]
